apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-kiro-demo
  region: us-west-2
  version: "1.33"

# Enable CloudWatch logging
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]

# Managed node group configuration
managedNodeGroups:
  - name: kiro-demo-nodes
    instanceType: m5.large
    desiredCapacity: 3
    minSize: 1
    maxSize: 5
    volumeSize: 20
    volumeType: gp3
    
    # SSH access disabled for simplicity
    # ssh:
    #   allow: true
    
    # IAM configuration
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true

# Add-ons to install
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest